# Purpose: Create release PR
# Trigger: workflow_run (CI) and pull_request (merged to main)

name: CREATE_RELEASE_PR

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write # create commits, tags, releases
  pull-requests: write # create release PR

jobs:
  create-release-pr:
    if: >
      github.repository_owner == 'JadejaHQ' && github.event_name ==
      'workflow_run' && github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0].merged == true &&
      github.event.workflow_run.pull_requests[0].base.ref == 'main'
    name: Create a release PR
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha }}

      # 2. Setup PNPM (to provide access to setup-node `cache: pnpm`)
      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 10.x.x
          run_install: false
          cache: true

      # 3. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org
          cache: pnpm

      # 4. Install dependencies (prevent when lockfile is out of sync)
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # 5. Create Release PR or Publish to NPM
      - name: Create Release PR or Publish to NPM
        uses: changesets/action@v1.7
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: true
          setupGitUser: false
          publish: false # important: do NOT publish here
        env:
          GITHUB_TOKEN: ${{ secrets.SHILPCSS_GITHUB_TOKEN }}
          NODE_ENV: production
